### ISSUE TITLE
Packager:  packager-update frequency as a configuration parameter

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus-api#18]
The packager updates the database on processing progress every time a grid is processed and added to the a DSS file.  This was intentional for MVP (Minimum Viable Product) development, but can result in numerous SQL queries run in rapid succession.

Update packager w/ a configuration parameter to control packager-update frequency.  This will support behaviors like "Update progress every 5 records, 10 records, etc."

**Comment by brettpalmberg** [comment]
@adamscarberry - I think you took care of this one?

**Comment by adamscarberry** [comment]
This was resolved last month.
